Zalicz.Mimuw/Models/Search/SearchViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Zalicz.Mimuw.Models.Course;

namespace Zalicz.Mimuw.Models.Search
{
    public class SearchViewModel
    {
        [Display(Name = "Course")]
        [Required(ErrorMessage = "Select a course.")]
        public string CourseShortName { get; set; }

        [Display(Name = "Taskset")]
        [Required(ErrorMessage = "Select a taskset.")]
        public string TasksetNameAndYear { get; set; }

        [Display(Name = "Include only tasks with solutions")]
        public bool RequireSolution { get; set; }

        public List<SelectListItem> Courses { get; set; }

        public SearchViewModel()
        {
        }

        public SearchViewModel(IEnumerable<CourseViewModel> courses)
        {
            Courses = courses.Select(c => c.ToSelectListItem()).ToList();
        }
    }
}

Zalicz.Mimuw/Controllers/CourseController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Services.Courses;
using Zalicz.Mimuw.Models.Course;

namespace Zalicz.Mimuw.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IStringLocalizer<CourseController> _localizer;

        public CourseController(ICourseService courseService, IStringLocalizer<CourseController> localizer)
        {
            _courseService = courseService;
            _localizer = localizer;
        }

        [HttpGet]
        public IActionResult CreateCourse() => View("CreateCourse", new CreateCourseViewModel());

        [HttpGet]
        public async Task<JsonResult> IsShortNameAvailable(string shortName) =>
            await _courseService.IsShortNameAvailableAsync(shortName)
                ? Json(true)
                : Json(string.Format(_localizer["Short name must be unique - course {0} already exists."], shortName));

        [HttpPost]
        public async Task<IActionResult> CreateCourse(CreateCourseViewModel createCourseViewModel)
        {
            await _courseService.CreateCourseAsync(createCourseViewModel.ToModel());

            return RedirectToAction("Search", "Home");
        }
    }
}

Zalicz.Mimuw/Controllers/Search/SearchController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Services.Courses;
using Services.Tasks;
using Zalicz.Mimuw.Controllers.Search.TaskSearchQueryBuilderExtensions;
using Zalicz.Mimuw.Models.Course;
using Zalicz.Mimuw.Models.Search;
using Zalicz.Mimuw.Models.Task;

namespace Zalicz.Mimuw.Controllers.Search
{
    public class SearchController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly ITaskService _taskService;

        public SearchController(ICourseService courseService, ITaskService taskService)
        {
            _courseService = courseService;
            _taskService = taskService;
        }

        [HttpGet]
        public async Task<IActionResult> Search()
        {
            var courses = (await _courseService.GetAllCoursesAsync()).Select(c => c.ToViewModel());
            var searchViewModel = new SearchViewModel(courses);

            return View("Search", searchViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> SearchTasks(SearchViewModel searchViewModel)
        {
            var query = _taskService.GetSearchQueryBuilder()
                .IncludeSolutionsAndReviews()
                .OrderByName()
                .AppendSearchViewModel(searchViewModel)
                .OrderSolutionsByUpvotesDescending()
                .OrderSolutionsNoNegativeReviewsFirst()
                .Build();

            var result = await _taskService.GetTasksAsync(query);

            return ViewComponent("SearchResult", result.Select(t => t.ToViewModel()).ToList());
        }
    }
}

Zalicz.Mimuw/Controllers/TaskController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Services.Courses;
using Services.Tasks;
using Zalicz.Mimuw.Cookies;
using Zalicz.Mimuw.Models.Course;
using Zalicz.Mimuw.Models.Task;

namespace Zalicz.Mimuw.Controllers
{
    public class TaskController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IStringLocalizer<TaskController> _localizer;
        private readonly ITaskService _taskService;
        private readonly ICookieProvider<UserIdCookie> _userIdCookieProvider;

        public TaskController(
            ICookieProvider<UserIdCookie> userIdCookieProvider,
            ICourseService courseService,
            ITaskService taskService,
            IStringLocalizer<TaskController> localizer)
        {
            _userIdCookieProvider = userIdCookieProvider;
            _courseService = courseService;
            _taskService = taskService;
            _localizer = localizer;
        }

        [HttpGet]
        public async Task<IActionResult> CreateTask()
        {
            var courses = (await _courseService.GetAllCoursesAsync()).Select(c => c.ToViewModel());
            var createTaskViewModel = new CreateTaskViewModel(courses);

            return View("CreateTask", createTaskViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateTask(CreateTaskViewModel createTaskViewModel)
        {
            var userId = _userIdCookieProvider.GetCookie().UserId.ToString();
            createTaskViewModel.Author = userId;

            await _taskService.CreateTaskAsync(createTaskViewModel.ToModel());

            return RedirectToAction("Search", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> EditTask(int taskId)
        {
            var task = await _taskService.GetTaskAsync(taskId);
            var editTaskViewModel = task.ToEditViewModel();

            return View("EditTask", editTaskViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditTask(EditTaskViewModel editTaskViewModel)
        {
            var userId = _userIdCookieProvider.GetCookie().UserId.ToString();
            editTaskViewModel.Author = userId;
            var editTaskModel = editTaskViewModel.ToModel();

            await _taskService.EditTaskAsync(editTaskModel);

            return RedirectToAction("Search", "Home");
        }

        [HttpPost]
        public JsonResult IsContentUpdateValid(string content, string originalContent) =>
            content.Equals(originalContent) ? Json(_localizer["No changes were made."].Value) : Json(true);
    }
}

Zalicz.Mimuw/Controllers/TasksetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Services.Courses;
using Services.Tasksets;
using Zalicz.Mimuw.Models.Course;
using Zalicz.Mimuw.Models.Taskset;

namespace Zalicz.Mimuw.Controllers
{
    public class TasksetController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IStringLocalizer<TasksetController> _localizer;
        private readonly ITasksetService _tasksetService;

        public TasksetController(
            ITasksetService tasksetService,
            ICourseService courseService,
            IStringLocalizer<TasksetController> localizer)
        {
            _tasksetService = tasksetService;
            _courseService = courseService;
            _localizer = localizer;
        }

        private static bool IsYearValid(int year) => year > 1900 && year <= DateTime.Now.Year + 1;

        [HttpGet]
        public async Task<JsonResult> IsTasksetNameAndYearValid(
            string courseShortName,
            string name,
            int year)
        {
            if (!IsYearValid(year))
            {
                return Json(_localizer["This year is invalid."]);
            }

            return !await _tasksetService.IsTasksetNameAndYearValidAsync(courseShortName, name, year)
                ? Json(
                    string.Format(
                        _localizer["A taskset with given name and year already exists for the {0} course."],
                        courseShortName))
                : Json(true);
        }

        [HttpGet]
        public async Task<IActionResult> CreateTaskset()
        {
            var courses = (await _courseService.GetAllCoursesAsync()).Select(c => c.ToViewModel());
            var createTasksetViewModel = new CreateTasksetViewModel(courses);

            return View("CreateTaskset", createTasksetViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateTaskset(CreateTasksetViewModel createTasksetViewModel)
        {
            await _tasksetService.CreateTasksetAsync(
                createTasksetViewModel.CourseShortName,
                createTasksetViewModel.ToModel());

            return RedirectToAction("Search", "Home");
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<SelectListItem>>> CourseTasksetsSelectListItems(
            string courseShortName) => new ActionResult<IEnumerable<SelectListItem>>(
            (await _courseService.GetAllTasksetsForCourseAsync(courseShortName)).Select(
                t => t.ToViewModel().ToSelectListItem()));
    }
}

Zalicz.Mimuw/Views/Search/Components/SearchResult/SearchResultViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Zalicz.Mimuw.Models.Task;

namespace Zalicz.Mimuw.Views.Search.Components.SearchResult
{
    public class SearchResultViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ICollection<TaskViewModel> taskViewModels) =>
            taskViewModels == null || !taskViewModels.Any()
                ? View("Empty", taskViewModels)
                : View("Results", taskViewModels);
    }
}

Zalicz.Mimuw/Views/Search/Search.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model Zalicz.Mimuw.Models.Search.SearchViewModel
@inject IViewLocalizer Localizer

<div class="task">
    <form id="search-form"
          asp-controller="Search" asp-action="SearchTasks"
          data-ajax="true" data-ajax-method="GET" data-ajax-mode="replace-with" data-ajax-update="#results"
          data-ajax-failure="renderErrorResponse($(xhr.responseText), $('#results'));">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="course-select" asp-for="CourseShortName"></label>
                <select id="course-select" class="form-control"
                        asp-for="CourseShortName" asp-items="Model.Courses" onchange="populateTasksetList($(this), $('#taskset-select'))"></select>
                <span asp-validation-for="CourseShortName" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label for="taskset-select" asp-for="TasksetNameAndYear"></label>
                <select id="taskset-select" class="form-control"
                        asp-for="TasksetNameAndYear"></select>
                <span asp-validation-for="TasksetNameAndYear" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-check">
                    <input id="require-solution-input" class="form-check-input"
                           asp-for="RequireSolution" type="checkbox"/>
                    <label for="require-solution-input" asp-for="RequireSolution" class="form-check-label"></label>
                </div>
            </div>
        </div>
        <div style="padding-top: 1%">
            <button id="search-form-submit-btn" class="btn btn-dark" type="submit">Zalicz!</button>
            <div id="create-dropdown" class="dropdown" style="float: right">
                <button id="create-button" class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @Localizer["Create new"]
                </button>
                <div class="dropdown-menu" aria-labelledby="create-button">
                    <a class="dropdown-item" asp-action="CreateCourse" asp-controller="Course">@Localizer["Course"]</a>
                    <a class="dropdown-item" asp-action="CreateTaskset" asp-controller="Taskset">@Localizer["Taskset"]</a>
                </div>
            </div>
        </div>
    </form>
</div>

<div id="results-parent">
    <div id="results-loader" style="display: none">
        <img src="~/images/loader-200px.svg" class="d-block mx-auto img-fluid" style="max-width: 200px" alt="Loading..."/>
    </div>
    <div id="results"></div>
</div>
<hr/>

<div id="create-task">
    <form asp-action="CreateTask" asp-controller="Task" method="get">
        <button id="create-task-button" class="btn btn-secondary btn-lg btn-block" style="height: 100px;", type="submit">
            @Localizer["Add a task"]
        </button>
    </form>
</div>

@section Scripts
{
    <script>
        $(document).ready(function() {
            populateTasksetList($('#course-select'), $('#taskset-select'));
        });
        // The populateTasksetList script has global set to false, so it will not trigger the loader, only the Search form will.
        $(document).ajaxStart(function() {
            $('#results').html('');
            $('#results-loader').show();
        });
        $(document).ajaxStop(function() {
            $('#results-loader').hide();
        });
    </script>
}